version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./videos:/videos

    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"